@startuml
skinparam ParticipantPadding 10
skinparam BoxPadding 10


== The Blockchain Africa Conference 2019 SSI User Story ==

group Install and configure uPort Mobile App

actor PERSON #purple
control "UPORT APP" as UPORT #purple
entity NOTIFICATION
control "QR CODE" as QR
actor VENDOR #green
boundary WEBAPI #blue
control "SAFBC APP" as SAFBC #red
actor "SAFBC REP" as REP #red

PERSON -> UPORT         : Install uPort App on mobile

box "ETHEREUM"
UPORT -> MAINNET #blue  : Request New Credential
MAINNET -> UPORT        : <color:red>Issue Ether Address & DID</color>
UPORT -> RINKEBY #grey  : Request New Credential
RINKEBY -> UPORT        : <color:red>Issue Ether Address & DID</color>
end box

PERSON -> UPORT : Complete User Profile
end group

== Sponsor Stand (Multiple Repeats?) ==

group Connect with Exibition Sponsor
PERSON -> VENDOR       : Proceed to Sponsor Stand and request login with uPort
QR -> UPORT             : Scan QR with uPort App
UPORT -> PERSON         : Request permission to share user data
PERSON -> PERSON        : Collect data
PERSON -> UPORT         : Data supply & Granted
UPORT -> WEBAPI        : share user data
WEBAPI -> WEBAPI      : Validate
WEBAPI -> PERSON       : Connected to Vendor
end group

group Attendance Verification

WEBAPI -> NOTIFICATION  : Issue Signed Attendance credentials
NOTIFICATION -> UPORT   : Receive credentials
UPORT -> PERSON         : Display Confirm
PERSON -> UPORT         : Confirm
UPORT -> UPORT          : Sign Credentials
end group

== Gift Claim ==

PERSON -> REP           : Go to SAFBC Stand
REP -> SAFBC            : Start Claim Process
SAFBC -> QR             : Display QR
QR -> UPORT             : Scan code
UPORT -> PERSON         : Request permission to share user data
PERSON -> UPORT         : Granted
UPORT -> SAFBC          : share user data
SAFBC -> SAFBC          : Validate claim
SAFBC -> REP            : Confirm Claim
REP -> PERSON           : Issue swag


@enduml
